In [2]:
import duckdb as ddb
import pandas as pd

In [3]:
con = ddb.connect("../air_quality.db")

con

In [4]:
df = con.query("select * from raw.air_quality_data where parameter in ('so2' ,'pm10' , 'pm25' )").to_df()

df.head()

,location_id,sensors_id,location,datetime,lat,lon,parameter,units,value,month,year,ingestion_datetime
0,9802,30644,Houston-9802,2025-01-01 11:30:00,40.269,-80.244,pm25,µg/m³,0.8,01,2025,2026-03-08 10:48:08.035357
1,9802,30644,Houston-9802,2025-01-01 12:30:00,40.269,-80.244,pm25,µg/m³,0.5,01,2025,2026-03-08 10:48:08.035357
2,9802,30644,Houston-9802,2025-01-01 13:30:00,40.269,-80.244,pm25,µg/m³,0.4,01,2025,2026-03-08 10:48:08.035357
3,9802,30644,Houston-9802,2025-01-01 14:30:00,40.269,-80.244,pm25,µg/m³,0.7,01,2025,2026-03-08 10:48:08.035357
4,9802,30644,Houston-9802,2025-01-01 15:30:00,40.269,-80.244,pm25,µg/m³,1.1,01,2025,2026-03-08 10:48:08.035357

In [5]:
df.info

<bound method DataFrame.info of      location_id  sensors_id      location            datetime     lat  \
0           9802       30644  Houston-9802 2025-01-01 11:30:00  40.269
1           9802       30644  Houston-9802 2025-01-01 12:30:00  40.269
2           9802       30644  Houston-9802 2025-01-01 13:30:00  40.269
3           9802       30644  Houston-9802 2025-01-01 14:30:00  40.269
4           9802       30644  Houston-9802 2025-01-01 15:30:00  40.269
..           ...         ...           ...                 ...     ...
739         9802       30644  Houston-9802 2025-02-01 06:30:00  40.269
740         9802       30644  Houston-9802 2025-02-01 07:30:00  40.269
741         9802       30644  Houston-9802 2025-02-01 08:30:00  40.269
742         9802       30644  Houston-9802 2025-02-01 09:30:00  40.269
743         9802       30644  Houston-9802 2025-02-01 10:30:00  40.269

        lon parameter  units  value month  year         ingestion_datetime
0   -80.244      pm25  µg/m³    0.8    01  2025 2026-03-08 10:48:08.035357
1   -80.244      pm25  µg/m³    0.5    01  2025 2026-03-08 10:48:08.035357
2   -80.244      pm25  µg/m³    0.4    01  2025 2026-03-08 10:48:08.035357
3   -80.244      pm25  µg/m³    0.7    01  2025 2026-03-08 10:48:08.035357
4   -80.244      pm25  µg/m³    1.1    01  2025 2026-03-08 10:48:08.035357
..      ...       ...    ...    ...   ...   ...                        ...
739 -80.244      pm25  µg/m³    4.3    01  2025 2026-03-08 10:48:08.035357
740 -80.244      pm25  µg/m³    4.7    01  2025 2026-03-08 10:48:08.035357
741 -80.244      pm25  µg/m³    5.2    01  2025 2026-03-08 10:48:08.035357
742 -80.244      pm25  µg/m³    3.6    01  2025 2026-03-08 10:48:08.035357
743 -80.244      pm25  µg/m³    2.1    01  2025 2026-03-08 10:48:08.035357

[744 rows x 12 columns]>

In [6]:
df.describe()

,location_id,sensors_id,datetime,lat,lon,value,year,ingestion_datetime
count,744.0,744.0,744,744.000,7.440000e+02,744.000000,744.0,744
mean,9802.0,30644.0,2025-01-16 23:00:00,40.269,-8.024400e+01,6.477285,2025.0,2026-03-08 10:48:08.035356
min,9802.0,30644.0,2025-01-01 11:30:00,40.269,-8.024400e+01,0.400000,2025.0,2026-03-08 10:48:08.035357
25%,9802.0,30644.0,2025-01-09 05:15:00,40.269,-8.024400e+01,4.000000,2025.0,2026-03-08 10:48:08.035357
50%,9802.0,30644.0,2025-01-16 23:00:00,40.269,-8.024400e+01,5.400000,2025.0,2026-03-08 10:48:08.035357
75%,9802.0,30644.0,2025-01-24 16:45:00,40.269,-8.024400e+01,7.100000,2025.0,2026-03-08 10:48:08.035357
max,9802.0,30644.0,2025-02-01 10:30:00,40.269,-8.024400e+01,24.700000,2025.0,2026-03-08 10:48:08.035357
std,0.0,0.0,NaN,0.000,1.422041e-14,4.069081,0.0,NaN

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 744 entries, 0 to 743
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   location_id         744 non-null    int64
 1   sensors_id          744 non-null    int64
 2   location            744 non-null    str
 3   datetime            744 non-null    datetime64[us]
 4   lat                 744 non-null    float64
 5   lon                 744 non-null    float64
 6   parameter           744 non-null    str
 7   units               744 non-null    str
 8   value               744 non-null    float64
 9   month               744 non-null    str
 10  year                744 non-null    int64
 11  ingestion_datetime  744 non-null    datetime64[us]
dtypes: datetime64[us](2), float64(3), int64(3), str(4)
memory usage: 69.9 KB

In [12]:
df.describe()

,location_id,sensors_id,datetime,lat,lon,value,year,ingestion_datetime
count,744.0,744.0,744,744.000,7.440000e+02,744.000000,744.0,744
mean,9802.0,30644.0,2025-01-16 23:00:00,40.269,-8.024400e+01,6.477285,2025.0,2026-03-08 10:48:08.035356
min,9802.0,30644.0,2025-01-01 11:30:00,40.269,-8.024400e+01,0.400000,2025.0,2026-03-08 10:48:08.035357
25%,9802.0,30644.0,2025-01-09 05:15:00,40.269,-8.024400e+01,4.000000,2025.0,2026-03-08 10:48:08.035357
50%,9802.0,30644.0,2025-01-16 23:00:00,40.269,-8.024400e+01,5.400000,2025.0,2026-03-08 10:48:08.035357
75%,9802.0,30644.0,2025-01-24 16:45:00,40.269,-8.024400e+01,7.100000,2025.0,2026-03-08 10:48:08.035357
max,9802.0,30644.0,2025-02-01 10:30:00,40.269,-8.024400e+01,24.700000,2025.0,2026-03-08 10:48:08.035357
std,0.0,0.0,NaN,0.000,1.422041e-14,4.069081,0.0,NaN

In [20]:
df[df.duplicated(subset=["location_id","parameter","units","value","datetime"])]

Empty DataFrame
Columns: [location_id, sensors_id, location, datetime, lat, lon, parameter, units, value, month, year, ingestion_datetime]
Index: []

In [21]:
df.groupby(by="parameter", as_index=False).count()

,parameter,location_id,sensors_id,location,datetime,lat,lon,units,value,month,year,ingestion_datetime
0,pm25,744,744,744,744,744,744,744,744,744,744,744

In [22]:
df.groupby(by="parameter", as_index=False).count()

,parameter,location_id,sensors_id,location,datetime,lat,lon,units,value,month,year,ingestion_datetime
0,pm25,744,744,744,744,744,744,744,744,744,744,744

In [23]:
con.close()